### ISSUE TITLE
Docker 客户端(Linux)配置代理 pull 镜像

### ISSUE THREAD

**Issue by greycodee** [greycodee/issues-blog#11]
## 原因
身处墙国，拉取镜像非常慢，所以要设置代理来提升拉取镜像的速度。

## 设置方法
- 创建文件夹
```shell
$ sudo mkdir -p /etc/systemd/system/docker.service.d
```
- 新建配置文件
```shell
$ sudo vim /etc/systemd/system/docker.service.d/http-proxy.conf
```
填入代理配置：
```toml
[Service]
Environment="HTTP_PROXY=http://127.0.0.1:7890"
Environment="HTTPS_PROXY=http://127.0.0.1:7890"
Environment="NO_PROXY=your-registry.com,10.10.10.10,*.example.com"
```
> 如果你自己建了私有的镜像仓库，需要 dockerd 绕过代理服务器直连，那么配置 `NO_PROXY` 变量，多个 `NO_PROXY` 变量的值用逗号分隔，而且可以使用通配符（*），极端情况下，如果 `NO_PROXY=*`，那么所有请求都将不通过代理服务器。如果不需要可以直接不设置这个变量

- 重启服务
```shell
$ sudo systemctl daemon-reload
$ sudo systemctl restart docker
```
- 检查配置
```shell
$ sudo systemctl show --property=Environment docker
[sudo] password for zheng:
Environment=HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890
```
设置成功🎉
